"""Public contact form submissions.

Creates ``contact_messages`` — a single table that stores enquiries
submitted via the ``/api/v1/contact/submit`` endpoint from anonymous
public visitors (no tenant FK — these arrive before any account exists).

Columns:
* ``id``           — UUID primary key, generated by Postgres gen_random_uuid().
* ``created_at``   — TIMESTAMPTZ NOT NULL DEFAULT now().
* ``name``         — VARCHAR(120) NOT NULL.
* ``email``        — VARCHAR(255) NOT NULL.
* ``topic``        — VARCHAR(32) NOT NULL DEFAULT 'general'.
* ``message``      — TEXT NOT NULL.
* ``ip``           — INET (nullable) — client IP captured at submission.
* ``user_agent``   — TEXT (nullable) — User-Agent header.
* ``notified_at``  — TIMESTAMPTZ (nullable) — set when the Telegram
                     notification POST succeeds; NULL means the
                     CONTACT_NOTIFY_URL env var was unset or the call
                     failed silently.

No RLS — table is pre-auth, same reasoning as ``rate_limit_counters``.

Revision ID: 0080_contact_messages
Revises: 0079_user_signup_plan
Create Date: 2026-04-29
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0080_contact_messages"
down_revision: str | None = "0079_user_signup_plan"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "contact_messages",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(120), nullable=False),
        sa.Column("email", sa.String(255), nullable=False),
        sa.Column(
            "topic",
            sa.String(32),
            nullable=False,
            server_default="general",
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("ip", sa.Text(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_contact_messages"),
    )
    op.create_index(
        "ix_contact_messages_created_at",
        "contact_messages",
        ["created_at"],
    )


def downgrade() -> None:
    op.drop_index("ix_contact_messages_created_at", table_name="contact_messages")
    op.drop_table("contact_messages")
