"""Extend pay_run_lines for full AU payroll + retarget employee_id FK.

Phase 1B. Sits between Phase 1A (employees + super_funds, 0110) and
Phase 2 (PAYG/super calc engine, 0112).

Two related changes shipped together:

1. ``pay_run_lines`` gains columns the calc engine needs:
   - ordinary_hours, overtime_hours
   - leave_hours_paid_annual, leave_hours_paid_personal, leave_hours_unpaid
   - allowances (JSONB), deductions (JSONB), paid_leave_lines (JSONB),
     lump_sums (JSONB), reportable_fringe_benefits (JSONB)
   - extra_pay (NUMERIC) — pre-computed value of an additional-pay
     calculation, see PAYG WH formula for back-pay / bonuses
   - ytd_gross, ytd_tax, ytd_super — running totals at the time
     of this pay run line
   - payg_scale_used (TEXT), payg_breakdown (JSONB) — audit trail
     of which PAYG formula produced ``tax``

2. ``pay_run_lines.employee_id`` is retargeted from ``contacts.id``
   to ``employees.id``. Safe because the live data set has zero
   rows (verified 2026-05-22 across all 5 stacks). The column stays
   NOT NULL — every pay-run line still requires an employee — but
   the FK now points at the right table.

Revision ID: 0111_pay_run_lines_extension
Revises: 0110_employees_and_super_funds
Create Date: 2026-05-22
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0112_pay_run_lines_extension"
down_revision: str | None = "0111_employees_and_super_funds"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # === 1. Retarget the employee_id FK to employees.id ================== #
    # Find the existing FK constraint name (it was auto-generated by 0090).
    # We DROP by the SA-suggested name; if it differs on a particular DB,
    # the migration falls back to a DROP CONSTRAINT IF EXISTS via raw SQL.
    op.execute(
        """
        DO $$
        DECLARE
            fk_name TEXT;
        BEGIN
            SELECT conname INTO fk_name
            FROM pg_constraint
            WHERE conrelid = 'pay_run_lines'::regclass
              AND contype  = 'f'
              AND conkey   = ARRAY[
                  (SELECT attnum FROM pg_attribute
                   WHERE attrelid = 'pay_run_lines'::regclass
                     AND attname  = 'employee_id')
              ]::smallint[];
            IF fk_name IS NOT NULL THEN
                EXECUTE 'ALTER TABLE pay_run_lines DROP CONSTRAINT ' || quote_ident(fk_name);
            END IF;
        END
        $$;
        """
    )
    op.create_foreign_key(
        "fk_pay_run_lines_employee_id_employees",
        source_table="pay_run_lines",
        referent_table="employees",
        local_cols=["employee_id"],
        remote_cols=["id"],
        ondelete="RESTRICT",
    )

    # === 2. New columns for the payroll calc engine ====================== #
    with op.batch_alter_table("pay_run_lines") as batch:
        batch.add_column(sa.Column(
            "ordinary_hours", sa.Numeric(8, 2),
            nullable=False, server_default="0",
        ))
        batch.add_column(sa.Column(
            "overtime_hours", sa.Numeric(8, 2),
            nullable=False, server_default="0",
        ))
        batch.add_column(sa.Column(
            "leave_hours_paid_annual", sa.Numeric(8, 2),
            nullable=False, server_default="0",
        ))
        batch.add_column(sa.Column(
            "leave_hours_paid_personal", sa.Numeric(8, 2),
            nullable=False, server_default="0",
        ))
        batch.add_column(sa.Column(
            "leave_hours_unpaid", sa.Numeric(8, 2),
            nullable=False, server_default="0",
        ))
        batch.add_column(sa.Column(
            "allowances",
            postgresql.JSONB(),
            nullable=False, server_default=sa.text("'[]'::jsonb"),
        ))
        batch.add_column(sa.Column(
            "deductions",
            postgresql.JSONB(),
            nullable=False, server_default=sa.text("'[]'::jsonb"),
        ))
        batch.add_column(sa.Column(
            "paid_leave_lines",
            postgresql.JSONB(),
            nullable=False, server_default=sa.text("'[]'::jsonb"),
        ))
        batch.add_column(sa.Column(
            "lump_sums",
            postgresql.JSONB(),
            nullable=False, server_default=sa.text("'{}'::jsonb"),
        ))
        batch.add_column(sa.Column(
            "reportable_fringe_benefits",
            postgresql.JSONB(),
            nullable=False, server_default=sa.text("'{}'::jsonb"),
        ))
        batch.add_column(sa.Column(
            "extra_pay", sa.Numeric(14, 2),
            nullable=False, server_default="0",
        ))
        batch.add_column(sa.Column(
            "ytd_gross", sa.Numeric(14, 2),
            nullable=False, server_default="0",
        ))
        batch.add_column(sa.Column(
            "ytd_tax", sa.Numeric(14, 2),
            nullable=False, server_default="0",
        ))
        batch.add_column(sa.Column(
            "ytd_super", sa.Numeric(14, 2),
            nullable=False, server_default="0",
        ))
        batch.add_column(sa.Column(
            "payg_scale_used", sa.String(32),
        ))
        batch.add_column(sa.Column(
            "payg_breakdown", postgresql.JSONB(),
        ))


def downgrade() -> None:
    # Drop added columns
    with op.batch_alter_table("pay_run_lines") as batch:
        batch.drop_column("payg_breakdown")
        batch.drop_column("payg_scale_used")
        batch.drop_column("ytd_super")
        batch.drop_column("ytd_tax")
        batch.drop_column("ytd_gross")
        batch.drop_column("extra_pay")
        batch.drop_column("reportable_fringe_benefits")
        batch.drop_column("lump_sums")
        batch.drop_column("paid_leave_lines")
        batch.drop_column("deductions")
        batch.drop_column("allowances")
        batch.drop_column("leave_hours_unpaid")
        batch.drop_column("leave_hours_paid_personal")
        batch.drop_column("leave_hours_paid_annual")
        batch.drop_column("overtime_hours")
        batch.drop_column("ordinary_hours")

    # Restore the original FK pointing at contacts.id
    op.drop_constraint(
        "fk_pay_run_lines_employee_id_employees",
        "pay_run_lines",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_pay_run_lines_employee_id_contacts",
        source_table="pay_run_lines",
        referent_table="contacts",
        local_cols=["employee_id"],
        remote_cols=["id"],
        ondelete="RESTRICT",
    )
