"""TSD golden-month byte-for-byte serializer test + persistence.

kmd-inf-tsd scope Packet 5 (``~/.claude/plans/kmd-inf-tsd-scope.md``
§4/§6/§7). Mirrors ``test_kmd_inf_golden.py``'s shape: reuses the EXACT
Packet-4 golden month (``test_tsd_generator.py``'s
``test_tsd_golden_month_lisa1_and_main`` scenario — same
``_make_employee``/``_make_pay_run``/``upsert_line``/
``finalize_ee_status_only`` helpers, same E1/E2 figures) via the same
cross-module import pattern ``test_tsd_generator.py`` itself established,
so this test proves the real generator + real serializer round-trip
byte-for-byte against the committed fixtures in ``tests/fixtures/tsd/``
(generated once from this exact scenario, see the fixture provenance
note below) — and that a persisted TSD return round-trips its
list-shaped ``figures`` JSONB.
"""
from __future__ import annotations

import uuid
from decimal import Decimal
from pathlib import Path

import pytest
from sqlalchemy import select

from saebooks.api.v1.auth import DEFAULT_TENANT_ID
from saebooks.db import AsyncSessionLocal
from saebooks.models.tax_period import TaxPeriod, TaxPeriodType
from saebooks.models.tax_return import TaxReturn, TaxReturnStatus
from saebooks.services.lodgement.tsd import (
    TsdReportingContext,
    build_tsd_lisa1_csv_document,
    build_tsd_main_csv_document,
    build_tsd_xml_document,
    generate_tsd,
    persist_tsd_return,
)
from saebooks.services.pay_runs_v2 import (
    PayLineInput,
    finalize_ee_status_only,
    upsert_line,
)
from tests.services.test_pay_runs_v2_ee import (
    _PAYMENT_DATE,
    _PERIOD_END,
    _PERIOD_START,
    _make_employee,
    _make_pay_run,
)
from tests.services.test_tax_return_generator import _make_ee_company

pytestmark = pytest.mark.postgres_only

_FIXTURES_DIR = Path(__file__).parent.parent.parent / "fixtures" / "tsd"
_REGCODE = "10123456"
_E1_ISIKUKOOD = "38001010000"
_E2_ISIKUKOOD = "48505010001"


async def _post_line(pay_run_id: uuid.UUID, employee_id: uuid.UUID) -> None:
    async with AsyncSessionLocal() as session:
        await upsert_line(
            session,
            pay_run_id=pay_run_id,
            line_input=PayLineInput(
                employee_id=employee_id, ordinary_hours=Decimal("1"), overtime_hours=Decimal("0"),
            ),
            tenant_id=DEFAULT_TENANT_ID, actor="test",
        )


async def _golden_listing():
    """Sets up + finalizes the Packet-4 golden month, returns the
    ``TsdListing`` the real generator produces for it."""
    company_id = await _make_ee_company(jurisdiction="EE")
    e1 = await _make_employee(
        company_id, name="E1 Low Wage", base_rate=Decimal("500.00"),
        isikukood=_E1_ISIKUKOOD,
    )
    e2 = await _make_employee(
        company_id, name="E2 Pillar Elect", base_rate=Decimal("2000.00"),
        pillar_ii_rate_percent=Decimal("6.0"), isikukood=_E2_ISIKUKOOD,
    )
    pay_run = await _make_pay_run(company_id)

    await _post_line(pay_run.id, e1.id)
    await _post_line(pay_run.id, e2.id)
    async with AsyncSessionLocal() as session:
        await finalize_ee_status_only(session, pay_run.id, tenant_id=DEFAULT_TENANT_ID, actor="test")

    async with AsyncSessionLocal() as session:
        listing = await generate_tsd(
            session, company_id=company_id, period_start=_PERIOD_START, period_end=_PERIOD_END,
        )
    return listing


async def test_tsd_golden_month_serialises_byte_for_byte() -> None:
    """The scope §6 golden month (E1 min-base-floor crosser, E2
    pillar-II-6% elective), posted for real, run through the real
    generator, serialised, and byte-compared against the fixtures.

    Fixture provenance: generated by running this exact scenario once
    and capturing the serializer's own output (base64-piped out of the
    ephemeral test container, which has no host bind-mount) — not
    hand-typed, same method ``test_kmd_inf_golden.py`` used. Any future
    change to the generator's row order, ``TsdMainTotals``/
    ``TsdLisa1Row`` field order, or a ``mapping.py`` PLACEHOLDER name
    requires regenerating these fixtures the same way.
    """
    listing = await _golden_listing()
    assert not listing.errors
    assert len(listing.lisa1) == 2

    ctx = TsdReportingContext(regcode=_REGCODE, period_start=_PERIOD_START, period_end=_PERIOD_END)
    xml_doc = build_tsd_xml_document(listing, ctx)
    main_csv = build_tsd_main_csv_document(listing, ctx)
    lisa1_csv = build_tsd_lisa1_csv_document(listing, ctx)

    assert xml_doc == (_FIXTURES_DIR / "golden.xml").read_bytes()
    assert main_csv == (_FIXTURES_DIR / "golden_main.csv").read_bytes()
    assert lisa1_csv == (_FIXTURES_DIR / "golden_lisa1.csv").read_bytes()


async def test_tsd_zero_rows_serialises_empty_lisa1_and_header_only_csv() -> None:
    """A period with no qualifying rows at all — no fixture needed, this
    is a small enough structural shape to assert inline (scope §6: "zero
    rows and N rows", mirrors ``test_kmd_inf_golden.py``'s equivalent)."""
    from lxml import etree

    from saebooks.services.lodgement.tsd import TsdListing, TsdMainTotals

    zero_main = TsdMainTotals(
        employee_count=0, total_gross=Decimal("0"), total_income_tax=Decimal("0"),
        total_unemployment_employee=Decimal("0"), total_unemployment_employer=Decimal("0"),
        total_social_tax=Decimal("0"), total_pillar_ii=Decimal("0"),
    )
    listing = TsdListing(
        company_id=uuid.uuid4(), period_start=_PERIOD_START, period_end=_PERIOD_END,
        main=zero_main,
    )
    ctx = TsdReportingContext(regcode=_REGCODE, period_start=_PERIOD_START, period_end=_PERIOD_END)

    xml_doc = build_tsd_xml_document(listing, ctx)
    root = etree.fromstring(xml_doc)
    ns = "urn:emta:PLACEHOLDER:tsd"
    assert len(root.find(f"{{{ns}}}Lisa1")) == 0

    lisa1_csv = build_tsd_lisa1_csv_document(listing, ctx)
    assert len(lisa1_csv.decode("utf-8").strip("\r\n").split("\r\n")) == 1  # header only


async def test_persist_tsd_return_writes_list_shaped_figures() -> None:
    """Scope §3.3's persistence decision, exercised end-to-end: a
    persisted TSD return's ``figures`` JSONB is list-shaped (``main`` +
    ``lisa1`` + ``errors``), unlike KMD's flat box-vector shape, and
    round-trips the golden month's own figures — mirrors
    ``test_persist_return_writes_tax_returns_row_with_ready_status``
    (test_tax_return_generator.py) adapted for the repeating-row shape."""
    listing = await _golden_listing()
    period_id = uuid.uuid4()
    async with AsyncSessionLocal() as session:
        session.add(
            TaxPeriod(
                id=period_id,
                company_id=listing.company_id,
                tenant_id=DEFAULT_TENANT_ID,
                jurisdiction="EST",
                period_type=TaxPeriodType.MONTHLY,
                period_start=_PERIOD_START,
                period_end=_PERIOD_END,
            )
        )
        await session.commit()

    async with AsyncSessionLocal() as session:
        row = await persist_tsd_return(
            session, listing, tenant_id=DEFAULT_TENANT_ID, period_id=period_id,
        )
        await session.commit()
        persisted_id = row.id

    async with AsyncSessionLocal() as session:
        persisted = (
            await session.execute(select(TaxReturn).where(TaxReturn.id == persisted_id))
        ).scalar_one()

    assert persisted.jurisdiction == "EE"
    assert persisted.return_type == "TSD"
    assert persisted.status == TaxReturnStatus.READY
    assert persisted.period_id == period_id
    assert persisted.figures["main"]["employee_count"] == 2
    assert persisted.figures["main"]["total_gross"] == "2500.00"
    assert persisted.figures["main"]["total_social_tax"] == "952.38"
    assert len(persisted.figures["lisa1"]) == 2
    # Critic round 2 fix: persisted figures carry a MASKED isikukood
    # (first 7 digits — century/sex + YYMMDD DOB — redacted), never the
    # plaintext value, so key by employee_id (still full plaintext in
    # ``listing`` in-memory / the file export) rather than isikukood.
    e1_id = str(next(r.employee_id for r in listing.lisa1 if r.isikukood == _E1_ISIKUKOOD))
    e2_id = str(next(r.employee_id for r in listing.lisa1 if r.isikukood == _E2_ISIKUKOOD))
    by_employee_id = {r["employee_id"]: r for r in persisted.figures["lisa1"]}
    assert by_employee_id[e1_id]["social_tax"] == "292.38"
    assert by_employee_id[e1_id]["isikukood"] == "XXXXXXX0000"
    assert by_employee_id[e2_id]["pillar_ii"] == "120.00"
    assert by_employee_id[e2_id]["isikukood"] == "XXXXXXX0001"
    assert persisted.figures["errors"] == []
