"""TSD Lisa 2-7 golden-file serializer tests (pure — no DB).

Mirrors ``test_tsd_golden.py``'s byte-for-byte discipline, adapted for
Module 1's serializer-only scope (no generator, so no DB round-trip — the
"golden" here is purely "does the serializer's own output stay pinned",
same posture as ``test_tsd_golden.py``'s fixture-provenance note). Reuses
the exact sample data each ``test_tsd_lisaN_serializer.py`` file already
defines (test-to-test import — the established convention in this
package, see ``test_tsd_golden.py``'s own imports from
``tests.services.test_pay_runs_v2_ee``).

Fixture provenance: generated by running this exact scenario once via
``SAEBOOKS_REGEN_FIXTURES=1`` and committing the serializer's own output —
not hand-typed. Any future change to a row/header dataclass's field order
or a ``mapping.py`` element-name constant requires regenerating.

Per the task's requested deliverable location, a copy of each golden is
ALSO written to ``~/records/saebooks/tsd-golden-lisaN.xml``/``.csv`` (human-
review artefact) — see ``_write_records_copy`` below. The in-repo copy
under ``tests/fixtures/tsd/`` is what this test actually compares against
(portable inside the docker test build context); the records copy is a
provenance/review artefact, not itself read by pytest.
"""
from __future__ import annotations

import os
from pathlib import Path

from saebooks.services.lodgement.tsd import TsdLisa3Header
from saebooks.services.lodgement.tsd.serializer import (
    build_tsd_lisa2_a_csv_document,
    build_tsd_lisa2_xml_document,
    build_tsd_lisa3_xml_document,
    build_tsd_lisa4_xml_document,
    build_tsd_lisa5_xml_document,
    build_tsd_lisa6_xml_document,
    build_tsd_lisa7_xml_document,
)
from tests.services.lodgement.test_tsd_lisa2_serializer import (
    _a_row as _lisa2_a_row,
)
from tests.services.lodgement.test_tsd_lisa2_serializer import (
    _b_row as _lisa2_b_row,
)
from tests.services.lodgement.test_tsd_lisa2_serializer import (
    _ctx as _lisa2_ctx,
)
from tests.services.lodgement.test_tsd_lisa2_serializer import (
    _inv_row as _lisa2_inv_row,
)
from tests.services.lodgement.test_tsd_lisa2_serializer import (
    _lisa2 as _lisa2_listing,
)
from tests.services.lodgement.test_tsd_lisa3_serializer import _ctx as _lisa3_ctx
from tests.services.lodgement.test_tsd_lisa4_serializer import (
    _ctx as _lisa4_ctx,
)
from tests.services.lodgement.test_tsd_lisa4_serializer import (
    _header as _lisa4_header,
)
from tests.services.lodgement.test_tsd_lisa5_serializer import (
    _ctx as _lisa5_ctx,
)
from tests.services.lodgement.test_tsd_lisa5_serializer import (
    _header as _lisa5_header,
)
from tests.services.lodgement.test_tsd_lisa6_serializer import (
    _ctx as _lisa6_ctx,
)
from tests.services.lodgement.test_tsd_lisa6_serializer import (
    _listing as _lisa6_listing,
)
from tests.services.lodgement.test_tsd_lisa7_serializer import (
    _ctx as _lisa7_ctx,
)
from tests.services.lodgement.test_tsd_lisa7_serializer import (
    _listing as _lisa7_listing,
)

_FIXTURES_DIR = Path(__file__).parent.parent.parent / "fixtures" / "tsd"
_RECORDS_DIR = Path.home() / "records" / "saebooks"


def _maybe_regen(path: Path, data: bytes) -> None:
    if os.environ.get("SAEBOOKS_REGEN_FIXTURES"):
        path.write_bytes(data)


def _write_records_copy(name: str, data: bytes) -> None:
    """Best-effort — the records dir is a human-review artefact, not a
    pytest dependency; never fail the test if it's unwritable (e.g. inside
    a docker build context with no home-dir bind-mount)."""
    if not os.environ.get("SAEBOOKS_REGEN_FIXTURES"):
        return
    try:
        _RECORDS_DIR.mkdir(parents=True, exist_ok=True)
        (_RECORDS_DIR / name).write_bytes(data)
    except OSError:
        pass


def test_lisa2_golden_xml_and_csv() -> None:
    listing = _lisa2_listing(
        a_rows=[_lisa2_a_row()], b_rows=[_lisa2_b_row()], inv_fond_rows=[_lisa2_inv_row()],
    )
    xml_doc = build_tsd_lisa2_xml_document(listing, _lisa2_ctx())
    csv_doc = build_tsd_lisa2_a_csv_document(listing.a_rows)
    _maybe_regen(_FIXTURES_DIR / "lisa2-golden.xml", xml_doc)
    _maybe_regen(_FIXTURES_DIR / "lisa2-a-golden.csv", csv_doc)
    _write_records_copy("tsd-golden-lisa2.xml", xml_doc)
    _write_records_copy("tsd-golden-lisa2.csv", csv_doc)
    assert xml_doc == (_FIXTURES_DIR / "lisa2-golden.xml").read_bytes()
    assert csv_doc == (_FIXTURES_DIR / "lisa2-a-golden.csv").read_bytes()


def test_lisa3_golden_xml() -> None:
    xml_doc = build_tsd_lisa3_xml_document(
        TsdLisa3Header(profit_removed_from_pe=__import__("decimal").Decimal("1000.00"),
                        treaty_country_code="FI"),
        _lisa3_ctx(),
    )
    _maybe_regen(_FIXTURES_DIR / "lisa3-golden.xml", xml_doc)
    _write_records_copy("tsd-golden-lisa3.xml", xml_doc)
    assert xml_doc == (_FIXTURES_DIR / "lisa3-golden.xml").read_bytes()


def test_lisa4_golden_xml() -> None:
    xml_doc = build_tsd_lisa4_xml_document(_lisa4_header(), _lisa4_ctx())
    _maybe_regen(_FIXTURES_DIR / "lisa4-golden.xml", xml_doc)
    _write_records_copy("tsd-golden-lisa4.xml", xml_doc)
    assert xml_doc == (_FIXTURES_DIR / "lisa4-golden.xml").read_bytes()


def test_lisa5_golden_xml() -> None:
    xml_doc = build_tsd_lisa5_xml_document(_lisa5_header(), _lisa5_ctx())
    _maybe_regen(_FIXTURES_DIR / "lisa5-golden.xml", xml_doc)
    _write_records_copy("tsd-golden-lisa5.xml", xml_doc)
    assert xml_doc == (_FIXTURES_DIR / "lisa5-golden.xml").read_bytes()


def test_lisa6_golden_xml() -> None:
    xml_doc = build_tsd_lisa6_xml_document(_lisa6_listing(), _lisa6_ctx())
    _maybe_regen(_FIXTURES_DIR / "lisa6-golden.xml", xml_doc)
    _write_records_copy("tsd-golden-lisa6.xml", xml_doc)
    assert xml_doc == (_FIXTURES_DIR / "lisa6-golden.xml").read_bytes()


def test_lisa7_golden_xml() -> None:
    xml_doc = build_tsd_lisa7_xml_document(_lisa7_listing(), _lisa7_ctx())
    _maybe_regen(_FIXTURES_DIR / "lisa7-golden.xml", xml_doc)
    _write_records_copy("tsd-golden-lisa7.xml", xml_doc)
    assert xml_doc == (_FIXTURES_DIR / "lisa7-golden.xml").read_bytes()
