"""KMD-INF golden-file byte-for-byte serializer test.

kmd-inf-tsd scope Packet 2 (``~/.claude/plans/kmd-inf-tsd-scope.md``
§4/§6/§7). Mirrors ``test_kmd_golden.py``'s shape: reuses the EXACT
Packet-1 golden period (``test_kmd_inf_generator.py``'s
``test_kmd_inf_golden_period`` scenario — same posting helpers, same
company/contact/document setup, same period) via the same cross-module
import pattern, so this test proves the real generator output round-trips
through the real serializer byte-for-byte against the committed fixtures
in ``tests/fixtures/kmd_inf/`` (generated once from this exact scenario,
see the fixture files' provenance note below).
"""
from __future__ import annotations

from datetime import date
from decimal import Decimal
from pathlib import Path

import pytest
from sqlalchemy import select

from saebooks.db import AsyncSessionLocal
from saebooks.models.account import Account, AccountType
from saebooks.models.contact import ContactType
from saebooks.models.tax_code import TaxCode
from saebooks.services.lodgement.kmd_inf import (
    KmdInfReportingContext,
    build_kmd_inf_part_a_csv_document,
    build_kmd_inf_part_b_csv_document,
    build_kmd_inf_xml_document,
    generate_kmd_inf,
)
from tests.services.lodgement.test_kmd_inf_generator import (
    _PERIOD_END,
    _PERIOD_START,
    _contact,
    _post_bill,
    _post_credit_note,
    _post_invoice,
)
from tests.services.test_tax_return_generator import _make_ee_company

pytestmark = pytest.mark.postgres_only

_FIXTURES_DIR = Path(__file__).parent.parent.parent / "fixtures" / "kmd_inf"
_REGCODE = "10123456"


async def test_kmd_inf_golden_period_serialises_byte_for_byte() -> None:
    """The Packet-1 golden period (P1 straddles via invoices+credit note,
    P2 stays under, P3 hits the exact €1,000 boundary, a no-code customer
    surfaces a data-quality error and is excluded, S1/S2 exercise the
    Part B deductible-only filter), posted for real, run through the real
    generator, serialised, and byte-compared against the fixtures.

    Fixture provenance: generated by running this exact scenario once and
    capturing the serializer's own output (base64-piped out of the
    ephemeral test container, which has no host bind-mount) — not
    hand-typed. Any future change to the generator's row order, the
    invoice/credit-note/bill numbering sequence, or a mapping.py
    PLACEHOLDER name requires regenerating these fixtures the same way.
    """
    company_id = await _make_ee_company(jurisdiction="EE")

    async with AsyncSessionLocal() as session:
        by_code = {
            code: aid for code, aid in (
                await session.execute(select(Account.code, Account.id).where(Account.company_id == company_id))
            ).all()
        }
        tax_by_type = {
            rt: tid for rt, tid in (
                await session.execute(select(TaxCode.reporting_type, TaxCode.id).where(TaxCode.company_id == company_id))
            ).all()
        }
        nd_tc = TaxCode(
            company_id=company_id,
            code="EE-EXEMPT-ND", name="EE exempt (non-deductible)", rate=Decimal("0.000"),
            tax_system="VAT", jurisdiction="EE", reporting_type="exempt",
            input_credit_recoverable=False,
        )
        session.add(nd_tc)
        session.add(Account(company_id=company_id, code="1-1200", name="Trade Debtors", account_type=AccountType.ASSET))
        session.add(Account(company_id=company_id, code="2-1200", name="Trade Creditors", account_type=AccountType.LIABILITY))
        await session.commit()
        nd_tax_code_id = nd_tc.id

    income_acct = by_code["4-1000"]
    expense_acct = by_code["5-1000"]
    standard_tc = tax_by_type["standard"]

    p1 = await _contact(company_id, "P1 Straddles Both Ways", ContactType.CUSTOMER, "10111111")
    p2 = await _contact(company_id, "P2 Stays Under", ContactType.CUSTOMER, "10222222")
    p3 = await _contact(company_id, "P3 Boundary", ContactType.CUSTOMER, "10333333")
    no_code = await _contact(company_id, "No-Code Customer", ContactType.CUSTOMER, None)
    s1 = await _contact(company_id, "S1 Deductible Supplier", ContactType.SUPPLIER, "10555555")
    s2 = await _contact(company_id, "S2 Stays Under", ContactType.SUPPLIER, "10666666")

    # Order matters — it drives the deterministic INV-/CN-/BILL- numbering
    # baked into the committed fixtures. Do not reorder without
    # regenerating.
    await _post_invoice(company_id, p1, income_acct, standard_tc, net=Decimal("700.00"), issue_date=date(2026, 2, 5))
    await _post_invoice(company_id, p1, income_acct, standard_tc, net=Decimal("500.00"), issue_date=date(2026, 2, 10))
    await _post_credit_note(company_id, p1, income_acct, standard_tc, net=Decimal("300.00"), issue_date=date(2026, 2, 15))
    await _post_invoice(company_id, p2, income_acct, standard_tc, net=Decimal("800.00"), issue_date=date(2026, 2, 6))
    await _post_invoice(company_id, p3, income_acct, standard_tc, net=Decimal("1000.00"), issue_date=date(2026, 2, 7))
    await _post_invoice(company_id, no_code, income_acct, standard_tc, net=Decimal("1300.00"), issue_date=date(2026, 2, 8))

    await _post_bill(company_id, s1, expense_acct, standard_tc, net=Decimal("1100.00"), issue_date=date(2026, 2, 9))
    await _post_bill(company_id, s1, expense_acct, nd_tax_code_id, net=Decimal("400.00"), issue_date=date(2026, 2, 11))
    await _post_bill(company_id, s2, expense_acct, standard_tc, net=Decimal("900.00"), issue_date=date(2026, 2, 12))

    async with AsyncSessionLocal() as session:
        listing = await generate_kmd_inf(
            session, company_id=company_id, period_start=_PERIOD_START, period_end=_PERIOD_END,
        )

    ctx = KmdInfReportingContext(regcode=_REGCODE, period_start=_PERIOD_START, period_end=_PERIOD_END)

    xml_doc = build_kmd_inf_xml_document(listing, ctx)
    csv_a = build_kmd_inf_part_a_csv_document(listing, ctx)
    csv_b = build_kmd_inf_part_b_csv_document(listing, ctx)

    assert xml_doc == (_FIXTURES_DIR / "golden.xml").read_bytes()
    assert csv_a == (_FIXTURES_DIR / "golden_part_a.csv").read_bytes()
    assert csv_b == (_FIXTURES_DIR / "golden_part_b.csv").read_bytes()


async def test_kmd_inf_zero_rows_serialises_empty_containers_and_header_only_csv() -> None:
    """A period with no qualifying rows at all — no fixture needed, this
    is a small enough structural shape to assert inline (scope §6: "zero
    rows and N rows")."""
    from saebooks.services.lodgement.kmd_inf import KmdInfListing
    import uuid
    from lxml import etree

    listing = KmdInfListing(
        company_id=uuid.uuid4(), period_start=_PERIOD_START, period_end=_PERIOD_END,
    )
    ctx = KmdInfReportingContext(regcode=_REGCODE, period_start=_PERIOD_START, period_end=_PERIOD_END)

    xml_doc = build_kmd_inf_xml_document(listing, ctx)
    root = etree.fromstring(xml_doc)
    ns = "urn:emta:PLACEHOLDER:kmdinf"
    assert len(root.find(f"{{{ns}}}OsaA")) == 0
    assert len(root.find(f"{{{ns}}}OsaB")) == 0

    csv_a = build_kmd_inf_part_a_csv_document(listing, ctx)
    csv_b = build_kmd_inf_part_b_csv_document(listing, ctx)
    assert len(csv_a.decode("utf-8").strip("\r\n").split("\r\n")) == 1  # header only
    assert len(csv_b.decode("utf-8").strip("\r\n").split("\r\n")) == 1
