"""ORM models for customer-facing integration state.

Currently contains:

* ``PaperlessWebhookSecret`` — per-tenant HMAC secret for validating
  inbound Paperless-ngx webhooks. Schema materialised by migration
  ``0088_paperless_webhook_secrets``.

Design notes
------------
* ``secret_ciphertext`` stores a Fernet-encrypted blob produced by
  ``services.crypto.encrypt_field``. BYTEA rather than TEXT because the
  value is opaque binary; callers decode via ``decrypt_field``.
* RLS is applied at the DB layer (migration 0088 enables
  ENABLE + FORCE ROW LEVEL SECURITY + ``tenant_isolation`` policy).
  The ORM model does NOT add a ``__table_args__`` RLS directive —
  that would only affect DDL generated by ``Base.metadata.create_all``,
  which is only used in tests. The migration is the authoritative DDL
  source for production.
"""
from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, LargeBinary, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from saebooks.db import Base


class PaperlessWebhookSecret(Base):
    """Per-tenant secret for validating inbound Paperless-ngx webhooks.

    Each tenant may have at most one active secret (``LIMIT 1`` queries
    in the webhook handler). The ``label`` column is informational —
    operators use it to distinguish multiple secrets during rotation
    (e.g. "production", "staging"). The migration/data layer does not
    enforce uniqueness on ``label``.
    """

    __tablename__ = "paperless_webhook_secrets"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=func.gen_random_uuid(),
    )
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    label: Mapped[str] = mapped_column(Text, nullable=False)
    secret_ciphertext: Mapped[bytes] = mapped_column(LargeBinary, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
