"""Generate a canonical SQLite schema dump for the Cashbook backend.

Usage (inside saebooks-dev-app-1):
    python scripts/dump_cashbook_schema.py

Writes ``db/cashbook.schema.sql`` at the repo root AND a copy at
``tests/db/cashbook.schema.sql`` (the latter is inside the volume
mount used by the dev container so the CI test can read it without
mounting the repo-root db/ dir).

Both files are identical — the repo-root copy is canonical; the
tests/db/ copy is the one pytest actually reads at runtime inside the
container.  Always re-run this script after any schema change and
commit both files.

All CREATE TABLE and CREATE INDEX statements are sorted alphabetically
by object name for deterministic diffs.  Running the script twice
without a schema change produces bit-identical output.
"""
from __future__ import annotations

import asyncio
import os
import sqlite3
import tempfile
from pathlib import Path

# Must be set before any saebooks import so env-gated code paths
# (resolve_tenant_id, mail outbox) initialise correctly.
os.environ.setdefault("SAEBOOKS_ENV", "test")
os.environ.setdefault("SAEBOOKS_MAIL_OUTBOX_DIR", "/tmp/saebooks-mail-outbox")

def _find_repo_root() -> Path:
    """Walk up from this file until we find pyproject.toml (the repo root).

    When the script is run in-place from the repo (``python scripts/…``) the
    parent-parent heuristic works fine.  When it's copied into /tmp and run
    there (e.g. via ``docker cp`` + ``docker exec``) we need a smarter probe.
    """
    # Prefer an explicit env override — useful for CI or unusual mounts.
    env_root = os.environ.get("SAEBOOKS_REPO_ROOT")
    if env_root:
        return Path(env_root)

    # Probe: walk up from __file__ looking for pyproject.toml.
    candidate = Path(__file__).resolve()
    for _ in range(8):  # don't loop forever
        candidate = candidate.parent
        if (candidate / "pyproject.toml").exists():
            return candidate

    # Last resort: the saebooks package itself is always importable in the
    # container; use its location to pin the repo root.
    import saebooks
    pkg_dir = Path(saebooks.__file__).resolve().parent
    return pkg_dir.parent


REPO_ROOT = _find_repo_root()
# Canonical path (repo root db/ dir).
OUTPUT_PATH = REPO_ROOT / "db" / "cashbook.schema.sql"
# Container copy — inside tests/ which IS mounted in saebooks-dev-app-1.
OUTPUT_PATH_TESTS = REPO_ROOT / "tests" / "db" / "cashbook.schema.sql"

HEADER = """\
-- AUTO-GENERATED by scripts/dump_cashbook_schema.py. Do not edit by hand. Re-run after schema changes.
--
-- Cashbook SQLite schema -- strict subset of the saebooks Postgres schema.
-- Generated by bootstrap_schema() (saebooks/db.py) against an empty in-memory
-- SQLite database, then sorted alphabetically by object name for deterministic
-- diffs.  Type narrowing rules (JSONB->JSON, UUID->CHAR(32), ARRAY->JSON) are
-- applied by the compile hooks in saebooks/db_types.py.
"""


async def _build_db(path: str) -> None:
    """Bootstrap an empty SQLite DB at *path* using the ORM metadata."""
    from sqlalchemy.ext.asyncio import create_async_engine

    from saebooks.db import bootstrap_schema

    url = f"sqlite+aiosqlite:///{path}"
    eng = create_async_engine(url)
    try:
        await bootstrap_schema(eng)
    finally:
        await eng.dispose()


def _extract_schema(path: str) -> str:
    """Read DDL statements from *path* and return sorted, normalised SQL."""
    conn = sqlite3.connect(path)
    try:
        tables = conn.execute(
            "SELECT name, sql FROM sqlite_master "
            "WHERE type = 'table' AND sql IS NOT NULL "
            "ORDER BY name"
        ).fetchall()
        indexes = conn.execute(
            "SELECT name, sql FROM sqlite_master "
            "WHERE type = 'index' AND sql IS NOT NULL "
            "ORDER BY name"
        ).fetchall()
    finally:
        conn.close()

    parts: list[str] = []

    for _name, sql in tables:
        # Normalise: ensure each statement ends with exactly one semicolon
        # and a trailing newline so diffs are clean.
        parts.append(sql.rstrip(";").rstrip() + ";")

    for _name, sql in indexes:
        parts.append(sql.rstrip(";").rstrip() + ";")

    return "\n\n".join(parts) + "\n"


def main(output_path: Path | None = None) -> None:
    # When an explicit path is given (e.g. from CLI), write only there.
    # Otherwise write to the canonical path AND the tests/db mirror.
    explicit = output_path is not None
    primary_out = output_path or OUTPUT_PATH

    primary_out.parent.mkdir(parents=True, exist_ok=True)

    with tempfile.NamedTemporaryFile(suffix=".db", delete=False) as f:
        tmp_path = f.name

    try:
        asyncio.run(_build_db(tmp_path))
        schema_sql = _extract_schema(tmp_path)
    finally:
        os.unlink(tmp_path)

    content = HEADER + "\n" + schema_sql

    primary_out.write_text(content, encoding="utf-8")

    # Count objects for the summary line.
    table_count = schema_sql.count("\nCREATE TABLE ")
    index_count = schema_sql.count("\nCREATE INDEX ")
    # Also count the first CREATE TABLE (no leading newline)
    if schema_sql.startswith("CREATE TABLE "):
        table_count += 1

    try:
        rel = primary_out.relative_to(REPO_ROOT)
    except ValueError:
        rel = primary_out

    print(
        f"Wrote {rel} "
        f"({table_count} tables, {index_count} indexes, "
        f"{len(content.splitlines())} lines)"
    )

    # Mirror to tests/db/ so the dev container pytest can read it without
    # needing the repo-root db/ dir mounted.
    if not explicit:
        OUTPUT_PATH_TESTS.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT_PATH_TESTS.write_text(content, encoding="utf-8")
        try:
            rel_t = OUTPUT_PATH_TESTS.relative_to(REPO_ROOT)
        except ValueError:
            rel_t = OUTPUT_PATH_TESTS
        print(f"  (mirror → {rel_t})")


if __name__ == "__main__":
    import sys

    # Allow ``python dump_cashbook_schema.py /some/output.sql`` for use
    # from outside the repo (e.g. ``docker exec … python /tmp/dump … /tmp/out.sql``).
    cli_out = Path(sys.argv[1]) if len(sys.argv) > 1 else None
    main(cli_out)
